### ISSUE TITLE
Add lang="en" to first wrapping container after the `<body>`

### ISSUE THREAD

**Issue by jkupczak** [ThemeMountain/acorn#2]
This was recently discussed in the #emailgeeks slack channel. Web clients like Gmail are going to strip and ignore both the `<html>` and `<body>` tags so the `lang` attribute gets lost. It seems like the best practice would be to apply the `lang` attribute to both the `<html>` tag and the main wrapping container after the `<body>` tag.

**Comment by cossssmin** [comment]
A PR is most welcome ;)

**Comment by cossssmin** [comment]
Closed in #3

**Comment by cossssmin** [comment]
🤔 I actually want to re-open this, because I've tested adding the `lang=""` attribute on the `<body>` tag instead, and that works fine in Gmail - as we know, it's transformed into a `<div>`.

For example:

![image](https://user-images.githubusercontent.com/1656595/47605477-870de700-da0f-11e8-87c1-158f79a79bd4.png)

What I'm not sure about is whether this would work the same in other web clients that remove the `<body>` tag. So I'm reopening the issue until it's clear.

**Comment by cossssmin** [comment]
So Yahoo! Mail web client transforms the `<body>` into a `<div>` without preserving any attributes. Since this isn't consistent, I guess we leave it as it is...
